git:
  depth: 2
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch:
    - master
  api_key:
    secure: MYMiGuwdZzaDun1ABjclb5jRYPGO+GWWoeROAZJdfa3uoX41G+S1Oy0C2j6vLP2/uS8n53C2Ic3tHXwoV1atnfUoCzTBdaxrqP0u6ZiLgL+4jzoWRWNsILqXXV05PyJG4VagwQ7SiIIHA6he0GTxajhI9xCZ6nELJmHGFfjkM3vjcVnRgehSwESIjJkj70AbO/+20FWeZTGRiVW6DoAJPEHsurO6i9GOtefxGI/tZYslovN5wLfDjLsOU3JVmnwJZToJ7RwbNOK7lLllfcsFlAVAWD3sFcjy1qJ9PkpVoH8MCeOj2D544Bz1bYym8WFFi326tHWbcu0VyaUq0KdPUQslTCmS6FF02/NEdsyLK6U0aXZJ9YfPbFTirAthr+nm/E69DhWyvQq4gY6QBbTb1fzAkf0RiG5/nCE80k90baqdjl8L2aW0FBIOVf5wvF3N8wqEmjcwg5g0CK3ZqKvpsgkg/K8Q+EKJ+APIM8APNhy8SWbW4HzPmANmfGijAqsxDsQyJth2f7UlnMso6Fb6zIbqiqCYpmhehBu93MqabWu2L6h+xej1gv0u1kpwYG4MDQ90zUs4W4dIwAzowLsPj/wyt4pL/EdPL0iw4zYlj2fmMmxBujiS03HeaLaaUL+lX103hdAg8p0guuMkSwloVhMER2dAXqieoG3cLS5CrZE=
script:
- nohup yarn test
