git:
  depth: 2
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch:
    - master
  api_key:
    secure: as1abL/rmoPdPd6HJW9KrrLnJkNfZdlObCIC0hkPMC+2HHfCIY6YNO0kLU+Yiu5Ejml7nbDCMNt4nvd3pKptjTUk/RivkaWhussZmQdTMVMSeY1YVN4Kfquh8+xg7OzfR60cqhJs0OcrEiBfjuz8OIvTNCAE/J7YYq7Frkmp7EjlgjG+Znkw8WGqzyeQ0pi+dl0IkL2bNrBnTp3tKVKay/VZwRg3DTsyOGS6fb8+Tp3o8DBvwZURgfV3nR5s5uy21ipMjh359KCZ399JQ1PIjChBHSJVZ91XZkdcM2SNfexRnsbF/a0X3QMCaUlwer2g1GCWtYl6YFyeu3323NWhhw1sGgtwIc2uEiAJOC+0eqoW+1aYWoODvjRdIUFTW/aRI9EMOv+LEJR7Gr7EICTsQjptgBVWJ38boZtT8/zDpuI9NUItDQr8D2qOwX2+MdXGuYQwkZXLf1o9tjzjNShdWUiJaTNPZ06S/IZMLsW9FpyDdvXeTHy2aWKJgQDIxtT+PEUNJyjFv8nnrDLlpLrxJSbJoxcaj12SGuFDGij/WaLUPShLvXAZlQtn0aDsPZcHZcn0NjepL+IxAf8shY0ND9qyUZixDu9Cmy5+4x9BpvNangQYa+TFB9HewOT/41CqIYDimgwyH0p8bFpwpEaOh/UKKFVEWGoUzgWJWVaKogw=
script:
- nohup yarn test
